import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import SideNav from './ui/sidenav'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {' '}
        <main className="flex h-screen flex-row overflow-hidden">
          <div className="w-64 flex-none">
            <SideNav />
          </div>
          <div className="flex-grow overflow-y-auto">{children}</div>
        </main>
      </body>
    </html>
  )
}
